"""empty message

Revision ID: d90f5cdbfcd8
Revises: 0d0080ec0846
Create Date: 2022-02-14 01:53:47.256369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90f5cdbfcd8'
down_revision = '0d0080ec0846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('restaurant_name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_email'), 'restaurant', ['email'], unique=True)
    op.create_index(op.f('ix_restaurant_id'), 'restaurant', ['id'], unique=True)
    op.create_index(op.f('ix_restaurant_name'), 'restaurant', ['name'], unique=True)
    op.create_index(op.f('ix_restaurant_restaurant_name'), 'restaurant', ['restaurant_name'], unique=True)
    op.create_index(op.f('ix_restaurant_username'), 'restaurant', ['username'], unique=True)
    op.create_table('menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('menu', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['menu'], ['restaurant.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=True)
    op.create_index(op.f('ix_menu_menu'), 'menu', ['menu'], unique=True)
    op.create_index(op.f('ix_menu_name'), 'menu', ['name'], unique=True)
    op.create_index(op.f('ix_menu_restaurant_id'), 'menu', ['restaurant_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('order_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.String(length=64), nullable=True),
    sa.Column('menu_id', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['product_name'], ['menu.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_description'), 'product', ['description'], unique=True)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=True)
    op.create_index(op.f('ix_product_image'), 'product', ['image'], unique=True)
    op.create_index(op.f('ix_product_menu_id'), 'product', ['menu_id'], unique=True)
    op.create_index(op.f('ix_product_product_name'), 'product', ['product_name'], unique=True)
    op.create_index(op.f('ix_product_restaurant_id'), 'product', ['restaurant_id'], unique=True)
    op.create_table('order_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['price'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_index('ix_roles_default', table_name='roles')
    op.drop_table('roles')
    op.add_column('user', sa.Column('role', sa.String(length=15), nullable=True))
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.drop_constraint('user_role_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_role_id_fkey', 'user', 'roles', ['role_id'], ['id'])
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_column('user', 'role')
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('name', name='roles_name_key')
    )
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    op.drop_table('order_product')
    op.drop_index(op.f('ix_product_restaurant_id'), table_name='product')
    op.drop_index(op.f('ix_product_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_menu_id'), table_name='product')
    op.drop_index(op.f('ix_product_image'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_description'), table_name='product')
    op.drop_table('product')
    op.drop_table('orders')
    op.drop_index(op.f('ix_menu_restaurant_id'), table_name='menu')
    op.drop_index(op.f('ix_menu_name'), table_name='menu')
    op.drop_index(op.f('ix_menu_menu'), table_name='menu')
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_restaurant_username'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_restaurant_name'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_name'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_id'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_email'), table_name='restaurant')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
